#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
BingguPack — OpenCrab Pack v1 finalize **dry-run 생성기** (v0.6 후보, 로컬 파일 생성만).

batch pack(candidate)을 OpenCrab Pack v1 required layout으로 **로컬에 조립**한다.
업로드/적용 단계가 아니다:
  - 외부 전송 0 (네트워크 코드 자체 없음) · OpenCrab upload/apply 0
  - **Neo4j 실행 0** — `neo4j/import.cypher`는 텍스트 파일 생성만, `export_status.json`은
    `{"status":"NOT_RUN"}` 스텁(실측은 별도 단계).
  - enum 확정(2026-06-10): license = {"scope":"personal","name":"MIT"} (L1).
    release_mode / entitlement 는 **비필드**(R1/E1) — manifest에 키 자체를 넣지 않는다.

생성 레이아웃 (pack v1 required 11):
  manifest.json / graph/nodes.jsonl / graph/edges.jsonl / evidence/index.jsonl
  quality/report.json / neo4j/import.cypher / neo4j/opencrab_ingest.jsonl
  neo4j/export_status.json / README.md / sample_queries.json / community_reports.json

CLI:
  python openbinggu_finalize_dryrun.py --selftest                      # synthetic/temp 전 과정 (권장)
  python openbinggu_finalize_dryrun.py --pack-dir <batch_pack> --out <빈 출력 디렉터리>
"""
from pathlib import Path
import os
import sys
import json
import hashlib
import shutil
import tempfile

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE, "scripts"))

from watcher_batch_m1 import scan_residual_pii  # noqa: E402  (기존 엔진 무수정 재사용)

LICENSE_L1 = {"scope": "personal", "name": "MIT"}
FORBIDDEN_MANIFEST_KEYS = ("release_mode", "entitlement")   # R1/E1 비필드 선언
REQUIRED_LAYOUT = [
    "manifest.json", "graph/nodes.jsonl", "graph/edges.jsonl", "evidence/index.jsonl",
    "quality/report.json", "neo4j/import.cypher", "neo4j/opencrab_ingest.jsonl",
    "neo4j/export_status.json", "README.md", "sample_queries.json", "community_reports.json",
]


def _jsonl_read(p):
    with open(p, encoding="utf-8") as f:
        return [json.loads(ln) for ln in f if ln.strip()]


def _jsonl_write(p, rows):
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


def _cypher_escape(s):
    return str(s).replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ")


def build_finalize_dryrun(pack_dir, out_dir):
    """batch pack → pack v1 레이아웃 로컬 조립. 반환 = report dict (외부 전송 0)."""
    d = os.path.abspath(pack_dir)
    out = os.path.abspath(out_dir)
    if os.path.isdir(out) and os.listdir(out):
        raise ValueError("out_dir_not_empty")
    with open(os.path.join(d, "manifest.json"), encoding="utf-8") as f:
        src_manifest = json.load(f)
    if src_manifest.get("pack_type") != "candidate":
        raise ValueError("pack_type_not_candidate")
    nodes = _jsonl_read(os.path.join(d, "nodes.jsonl"))
    edges = _jsonl_read(os.path.join(d, "edges.jsonl"))
    chunks = _jsonl_read(os.path.join(d, "evidence_chunk.jsonl"))

    # PII 잔존 재스캔 (fail-closed, kind만)
    pii = sorted({k for c in chunks for k in scan_residual_pii(c.get("text", ""))})
    if pii:
        return {"gate": "NO-GO", "reason": "pii_residual", "pii_kinds": pii}

    # canonical graph (JSONL이 canonical — Neo4j는 검증/재현용)
    _jsonl_write(os.path.join(out, "graph", "nodes.jsonl"), nodes)
    _jsonl_write(os.path.join(out, "graph", "edges.jsonl"), edges)
    ev_index = [{"evidence_id": c["item_id"],
                 "source_hash": hashlib.sha256(c.get("text", "").encode("utf-8", "replace")).hexdigest()[:16],
                 "candidate": True} for c in chunks]
    _jsonl_write(os.path.join(out, "evidence", "index.jsonl"), ev_index)

    # manifest — L1 license / R1·E1 비필드 (키 자체 미기입)
    manifest = {
        "format_version": "opencrab-pack-v1",
        "pack_id": src_manifest["pack_id"],
        "pack_type": "candidate",
        "promotion_allowed_default": False,
        "license": dict(LICENSE_L1),
        "counts": {"nodes": len(nodes), "edges": len(edges), "evidence": len(ev_index)},
        "finalize_stage": "dry-run-local-only",
    }
    with open(os.path.join(out, "manifest.json"), "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=1)

    # quality report
    os.makedirs(os.path.join(out, "quality"), exist_ok=True)
    with open(os.path.join(out, "quality", "report.json"), "w", encoding="utf-8") as fq:
        json.dump({"counts": manifest["counts"], "pii_residual": 0,
                   "candidate_all": all((n.get("properties") or {}).get("candidate") is True for n in nodes),
                   "promotion_allowed_any_true": any(n.get("promotion_allowed") is True for n in nodes)},
                  fq, ensure_ascii=False, indent=1)

    # neo4j 산출물 — 파일 생성만 (실행 0)
    cy = ["// generated by finalize dry-run — NOT executed (Neo4j run deferred)"]
    for n in nodes:
        cy.append(f"CREATE (:Candidate {{id:'{_cypher_escape(n['id'])}', node_type:'{_cypher_escape(n.get('node_type',''))}'}});")
    for e in edges:
        cy.append(f"MATCH (a {{id:'{_cypher_escape(e['source'])}'}}), (b {{id:'{_cypher_escape(e['target'])}'}}) "
                  f"CREATE (a)-[:{str((e.get('properties') or {}).get('relation','related')).upper().replace('-','_')}]->(b);")
    os.makedirs(os.path.join(out, "neo4j"), exist_ok=True)
    with open(os.path.join(out, "neo4j", "import.cypher"), "w", encoding="utf-8") as f:
        f.write("\n".join(cy) + "\n")
    _jsonl_write(os.path.join(out, "neo4j", "opencrab_ingest.jsonl"),
                 [{"kind": "node", "id": n["id"]} for n in nodes]
                 + [{"kind": "edge", "id": e["id"]} for e in edges])
    with open(os.path.join(out, "neo4j", "export_status.json"), "w", encoding="utf-8") as f:
        json.dump({"status": "NOT_RUN", "note": "Neo4j execution deferred (dry-run generates files only)"},
                  f, ensure_ascii=False, indent=1)

    # README / sample_queries / community_reports
    with open(os.path.join(out, "README.md"), "w", encoding="utf-8") as f:
        f.write(f"# Pack: {manifest['pack_id']} (finalize dry-run output)\n\n"
                f"- candidate-only pack (promotion_allowed=false)\n"
                f"- license: {LICENSE_L1['name']} (scope: {LICENSE_L1['scope']})\n"
                f"- canonical graph = graph/*.jsonl (Neo4j artifacts are for local verification only)\n"
                f"- This layout was assembled locally. No upload was performed.\n")
    with open(os.path.join(out, "sample_queries.json"), "w", encoding="utf-8") as f:
        json.dump([{"q": "MATCH (n:Candidate) RETURN count(n)", "purpose": "node count check"},
                   {"q": "MATCH ()-[r]->() RETURN count(r)", "purpose": "edge count check"}],
                  f, ensure_ascii=False, indent=1)
    with open(os.path.join(out, "community_reports.json"), "w", encoding="utf-8") as f:
        json.dump({"reports": [], "note": "empty for personal-track dry-run"}, f, ensure_ascii=False, indent=1)

    missing = [p for p in REQUIRED_LAYOUT if not os.path.isfile(os.path.join(out, p))]
    return {"gate": "GO" if not missing else "NO-GO", "out_id": hashlib.sha256(out.encode()).hexdigest()[:8],
            "layout_missing": missing, "counts": manifest["counts"], "license": manifest["license"],
            "forbidden_keys_absent": all(k not in manifest for k in FORBIDDEN_MANIFEST_KEYS)}


# ── selftest (synthetic/temp 전용) ───────────────────────────────────────────

def _make_synthetic_pack(tmp, pack_id="fin_toy", n=3, pii=False):
    d = os.path.join(tmp, pack_id); os.makedirs(d, exist_ok=True)
    nodes, edges, chunks = [], [], []
    for i in range(n):
        sent = f"toy 판단 {i}: 마진 확보 시 진행"
        if pii and i == 0:
            sent += " 연락처 " + "-".join(("010", "1234", "5678"))   # 조각조합 fixture
        nid, eid, vid = f"node:FIN:{i}", f"edge:FIN:{i}", f"EVC-FIN-{i}"
        nodes.append({"id": nid, "node_type": "Claim", "evidence_refs": [vid], "promotion_allowed": False,
                      "properties": {"candidate": True, "label_kind": "판단", "sentence": sent,
                                     "relation": None}})
        edges.append({"id": eid, "source": vid, "target": nid, "evidence_refs": [vid],
                      "promotion_allowed": False,
                      "properties": {"candidate": True, "relation": "evidence_supports", "sentence": sent}})
        chunks.append({"item_id": vid, "source": f"toy_src_{i}", "text": sent})
    with open(os.path.join(d, "manifest.json"), "w", encoding="utf-8") as f:
        json.dump({"format_version": "opencrab-pack-v1", "pack_id": pack_id,
                   "pack_type": "candidate", "promotion_allowed_default": False}, f)
    for name, rows in (("nodes.jsonl", nodes), ("edges.jsonl", edges), ("evidence_chunk.jsonl", chunks)):
        _jsonl_write(os.path.join(d, name), rows)
    return d


def _selftest():
    print("=" * 80)
    print("finalize dry-run selftest (synthetic/temp only · 외부 전송 0 · Neo4j 실행 0)")
    print("=" * 80)
    tmp = tempfile.mkdtemp(prefix="binggupack_finalize_")
    results = []

    def rec(cid, name, ok):
        results.append(ok)
        print(f"  [{'OK' if ok else 'NG'}] {cid} {name}")

    try:
        pack = _make_synthetic_pack(tmp)
        out1 = os.path.join(tmp, "out1")
        r = build_finalize_dryrun(pack, out1)
        rec("F1", "레이아웃 11종 전부 생성 + GATE=GO", r["gate"] == "GO" and not r["layout_missing"])
        m = json.loads(Path(os.path.join(out1, 'manifest.json')).read_text(encoding='utf-8'))
        rec("F2", "license = L1 {personal, MIT}", m["license"] == LICENSE_L1)
        rec("F3", "R1/E1: release_mode·entitlement 키 부재",
            all(k not in m for k in FORBIDDEN_MANIFEST_KEYS) and r["forbidden_keys_absent"])
        rec("F4", "canonical graph counts 일치",
            m["counts"] == {"nodes": 3, "edges": 3, "evidence": 3})
        cy = Path(os.path.join(out1, 'neo4j', 'import.cypher')).read_text(encoding='utf-8')
        rec("F5", "cypher: CREATE 노드 3 + 엣지 3 (텍스트 생성만)",
            cy.count("CREATE (:Candidate") == 3 and cy.count("CREATE (a)-[") == 3)
        es = json.loads(Path(os.path.join(out1, 'neo4j', 'export_status.json')).read_text(encoding='utf-8'))
        rec("F6", "export_status = NOT_RUN (Neo4j 미실행)", es["status"] == "NOT_RUN")
        q = json.loads(Path(os.path.join(out1, 'quality', 'report.json')).read_text(encoding='utf-8'))
        rec("F7", "quality: candidate_all=True + promotion true 0건",
            q["candidate_all"] and not q["promotion_allowed_any_true"])
        # PII pack → NO-GO (출력 미생성)
        out2 = os.path.join(tmp, "out2")
        r2 = build_finalize_dryrun(_make_synthetic_pack(tmp, "fin_pii", pii=True), out2)
        rec("F8", "PII 잔존 → NO-GO + kind만", r2["gate"] == "NO-GO" and r2["reason"] == "pii_residual")
        # 비어있지 않은 out 거부
        try:
            build_finalize_dryrun(pack, out1)
            rec("F9", "비어있지 않은 out_dir 거부", False)
        except ValueError as ex:
            rec("F9", "비어있지 않은 out_dir 거부", str(ex) == "out_dir_not_empty")
        # 결정적 재생성 (동일 입력 → 동일 manifest counts/license)
        out3 = os.path.join(tmp, "out3")
        r3 = build_finalize_dryrun(pack, out3)
        m3 = json.loads(Path(os.path.join(out3, 'manifest.json')).read_text(encoding='utf-8'))
        rec("F10", "결정적 재생성 (manifest 동일)", r3["gate"] == "GO" and m3 == m)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    n_pass = sum(results)
    print("-" * 80)
    print(f"RESULT: {n_pass}/{len(results)} PASS   upload=0 apply=0 neo4j_run=0 외부전송=0")
    print(f"GATE: {'GO' if n_pass == len(results) else 'NO-GO'}")
    return 0 if n_pass == len(results) else 1


def main():
    args = sys.argv[1:]
    if not args or args[0] == "--selftest":
        return _selftest()
    pack_dir = out = None
    for i, a in enumerate(args):
        if a == "--pack-dir" and i + 1 < len(args): pack_dir = args[i + 1]
        if a == "--out" and i + 1 < len(args): out = args[i + 1]
    if not pack_dir or not out:
        print(__doc__); return 2
    r = build_finalize_dryrun(pack_dir, out)
    print(json.dumps(r, ensure_ascii=False, indent=1))
    print("NOTE: 로컬 조립만 수행. upload/apply/Neo4j 실행은 별도 단계.")
    return 0 if r.get("gate") == "GO" else 1


if __name__ == "__main__":
    sys.exit(main())
